# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='after',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='before',
        ),
        migrations.AddField(
            model_name='modification',
            name='script',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
