# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0003_auto_20160120_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='ecu',
        ),
        migrations.AddField(
            model_name='modification',
            name='ecu',
            field=models.ManyToManyField(to='ess.ECU'),
        ),
    ]
